import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/section/Navbar";
import Header from "./components/section/Header";
import Footer from "./components/section/Footer";
import { Poppins, Open_Sans, Lato, Manrope } from "next/font/google";
import { Toaster } from "react-hot-toast";
import StoreProvider from "./StoreProvider";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
});

const arial = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-arial",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-lato",
});

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-manrope",
});

export const metadata = {
  title: "foodtrove ecommarce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${arial.variable} ${lato.variable}  ${manrope.variable} ${inter.className}`}
      >
        <StoreProvider>
          <Navbar />
          <Header />
          {children}
          <Footer />
          <Toaster position="bottom-left" reverseOrder={false} />
        </StoreProvider>
      </body>
    </html>
  );
}
